export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import styles from './layout.module.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.shell}>{children}</body>
    </html >
  )
}
